name: Easemob
title: Easemob 
org: Organization
base_url: ''

slim:
  :encoding: UTF-8
  :pretty: true
  
profiles:
  development:
    minify: false
    disqus_developer: true
    dev: true
    deploy:
      dummy:
  production:
    base_url: http://developer.easemob.com
    #disqus_developer: false
    # google_analytics: UA-1234567-1
    minify: true
    slim:
      :encoding: UTF-8
      :pretty: false
    
    deploy:
      host: ebs5
      path: /home/easemob/apps/data/nginx/developer.easemob.com
      uncommitted: true
